export const Governorats = [
    'Ariana',
    'Béja',
    'Sousse',
    'Bizerte',
    'Gabés',
    'Nabeul',
    'Jendouba',
    'Kairouan',
    'Zaghouan',
    'Kebili',
    'Kef',
    'Mahdia',
    'Manouba',
    'Medenine',
    'Monastir',
    'Gafsa',
    'Sfax',
    'Sidi Bouzid',
    'Siliana',
    'Ben Arous',
    'Tataouine',
    'Tozeur',
    'Tunis',
    'Kasserine'
]